-- 여기는 RentBook root 로 접속한 화면
CREATE DATABASE rentBookDB;
use rentBookDB;
CREATE TABLE tbl_books(
	B_CODE	VARCHAR(13)		PRIMARY KEY,
	B_NAME	VARCHAR(125)	NOT NULL,
	B_AUTHOR	VARCHAR(125)	NOT NULL,	
	B_COMP	VARCHAR(125),
	B_YEAR	INT	NOT NULL,
	B_IPRICE	INT,
	B_RPRICE	INT	NOT NULL	
);
DESC tbl_books;
DROP TABLE tbl_books;
SHOW TABLES;

INSERT INTO tbl_books(
B_CODE,B_NAME,B_AUTHOR,B_COMP,B_YEAR,B_IPRICE,B_RPRICE
) VALUES (
'001','남극의 눈물','뗑컨','뗑컨사','2010','30000','3000'
);
SELECT * FROM tbl_books;
DELETE FROM tbl_books WHERE B_CODE = '';

USE rentbookDB;

CREATE TABLE tbl_members (
	M_CODE	VARCHAR(6)		PRIMARY KEY,
	M_NAME	VARCHAR(125)	NOT NULL,	
	M_TEL	VARCHAR(15)	NOT NULL,	
	M_ADDR	VARCHAR(125)		
);
INSERT INTO tbl_members(m_code,m_name,m_tel,m_addr) VALUES('000001','홍길동','010-1111-1111','광주광역시');
DESC tbl_members;
SELECT * FROM tbl_members;
DROP TABLE tbl_members;

CREATE TABLE tbl_rent_book (
	RENT_SEQ	BIGINT		PRIMARY KEY	AUTO_INCREMENT,
	RENT_DATE	VARCHAR(10)	NOT NULL,
	RENT_RETURN_DATE	VARCHAR(10)	NOT NULL,
	RENT_BCODE	VARCHAR(13)	NOT NULL,		
	RENT_MCODE	VARCHAR(6)	NOT NULL,		
	RENT_RETURN_YN	VARCHAR(1),			
	RENT_POINT	INT,			
	RENT_PRICE	INT			
);
DESC tbl_rent_book;