-- 여기는 RentBook root 로 접속한 화면
CREATE DATABASE rentBookDB;
use rentBookDB;
CREATE TABLE tbl_books(
	B_CODE	VARCHAR(13)		PRIMARY KEY,
	B_NAME	VARCHAR(125)	NOT NULL,
	B_AUTHOR	VARCHAR(125)	NOT NULL,	
	B_COMP	VARCHAR(125),
	B_YEAR	INT	NOT NULL,
	B_IPRICE	INT,
	B_RPRICE	INT	NOT NULL	
);
DESC tbl_books;
DROP TABLE tbl_books;
SHOW TABLES;

INSERT INTO tbl_books(
B_CODE,B_NAME,B_AUTHOR,B_COMP,B_YEAR,B_IPRICE,B_RPRICE
) VALUES (
'001','남극의 눈물','뗑컨','뗑컨사','2010','30000','3000'
);
SELECT * FROM tbl_books;
DELETE FROM tbl_books WHERE B_CODE = '';